#include<iostream>
using namespace std;
int main()
{
string g;
g="God is great";
cout<<"First character:"<<g.front()<<endl;
cout<<"Last character:"<<g.back()<<endl;
cout<<"By position:"<<g.at(4)<<endl;
g+="!!";
cout<<g<<endl;
g.append(" Ujjai");
cout<<g<<endl;
g.push_back('n');
cout<<g<<endl;
g.append(10,'A');
cout<<g<<endl;
g.assign("Ujjain is the city of gods");
cout<<g<<endl;
g.assign("God is great",6);
cout<<g<<endl;
g.assign(10,'A');
cout<<g<<endl;
g="I live in ujjain";
cout<<g<<endl;
string i;
i.assign(g,2,4);
cout<<i<<endl;
g.insert(0,"God is great.");
cout<<g<<endl;
string m="Cool & ";
g.insert(7,m);
cout<<g<<endl;
m="Sameer is a person";
m.insert(12,g,7,5);
cout<<m<<endl;
m.insert(16,"Fool",3);
cout<<m<<endl;
m="Mohan is a bad person";
m.insert(5,10,'-');
cout<<m<<endl;
m.pop_back();
m.pop_back();
m.pop_back();
cout<<m<<endl;
m.erase();
cout<<m<<endl;
cout<<"*******"<<endl;
cout<<m.empty()<<endl;
m="Ujjain is the city of gods";
m.erase(0,10);
cout<<m<<endl;
m.erase(8);
cout<<m<<endl;
m="I live in Ahmedabad.Ahmedadabad is the city of gods";
string f="Ahmedabad";
string k="Ujjain";
cout<<"******replace() function*******"<<endl;
m.replace(10,f.length(),k);
cout<<m<<endl;
m.replace(17,f.length(),k);
cout<<m<<endl;
m.replace(17,6,10,'_');
cout<<m<<endl;
g="Cool";
m.swap(g);
cout<<m<<endl;
cout<<g<<endl;

return 0;
}